language: php
php:
- 5.4
- 5.5
- 5.6
- hhvm
- nightly
install: composer install
env:
  global:
    secure: StoO5Z4yhXcs2SIWV/tUGLtTkPN4KycSvwE5M5JwWPJhzbLMKdzxFQrVCB1GrFRkWzpxX1xJSJbiNKMhBS+YdhqSuic8/fq7beBP6NQ8jOIY3obllFg5K73UjrgXNsmV3qL70xWfj5/N3OiUW2K1T1kxJ5CrgTzwEmabWbikelSPEdAUhXLtcQw3rE97F1z1lgtRt321MnvClWfn+f6y9K6/OhtsZODpv11yH+bfVFb13aZ3iNQozZnQ/bVGjeLoKa3oBrrNCzp7I4oYdLFdr08ORdnAzfwdlOFUAooLP9vz1RczHbQXbMpw9WOURM0zHv9LGLHMVlvYqIAGjqfjswQwetuCYtOwehMO5vqQUKvvQDYm2Pt++Qywi0s1Z0q3qI8nhNr4bVR0l33KxYc2pVVqKx0N5XmVPQMhNzDcQoKqVwJUaEnORhlQaq14lnlrtm+qsluwT6dr3lYSTKM1ucjN40zI7ytwOWIqPd+KB805rlAaAr6TJUYgNniQPMFt3hSq8DQIjvrbmMsJbPfKlpYIz6nC31jI1IKaY6mo1SAVACy1zSh1c+MNlLzVMEnVBDThtxISBHlp5uhtk4J13y9f+ra5BNVP/tSR9VajKVT84GLFPmdst4nSmzTYnf90oW6l7S7zPgfl7zeFAyp9bGRNSvAzWgYLSnKmLh55Aa4=
